<?php

namespace App\Services;

/**
 * BIZMAPSの業種テキスト → TRUSTEPS industries.slug に変換するマッパー
 *
 * 使い方:
 *   $mapper = new BizmapsIndustryMapper();
 *   $slug = $mapper->resolve('建設・建築', '塗装工事・外装・エクステリア工事');
 *   // => 'construction_paint'
 */
class BizmapsIndustryMapper
{
    /**
     * BIZMAPSの中分類テキスト → TRUSTEPS slug
     * 大分類は中分類で解決できない場合のフォールバック用
     */
    private const SUBCATEGORY_MAP = [

        // ===== 建設・建築 =====
        'ゼネコン'                          => 'construction_builder',
        '住宅建築・開発'                    => 'construction_builder',
        '注文型住宅建築'                    => 'construction_builder',
        '分譲型住宅建築'                    => 'construction_builder',
        'リフォーム'                        => 'construction_reform',
        '修繕工事'                          => 'construction_reform',
        '耐震工事・地盤改良工事'            => 'construction_reform',
        '耐震診断'                          => 'construction_reform',
        '塗装工事・外装・エクステリア工事'  => 'construction_paint',
        '建築塗装'                          => 'construction_paint',
        '外構・エクステリア工事'            => 'construction_exterior',
        '造園'                              => 'construction_exterior',
        '造園工事'                          => 'construction_exterior',
        '屋上緑化'                          => 'construction_exterior',
        '電気設備工事'                      => 'construction_equipment',
        'その他電気設備工事'               => 'construction_equipment',
        '空調設備工事'                      => 'construction_equipment',
        '住宅設備'                          => 'construction_equipment',
        '住宅・事業所向け設備'             => 'construction_equipment',
        '通信設備工事'                      => 'construction_equipment',
        '電設資材'                          => 'construction_equipment',
        '太陽光発電'                        => 'construction_equipment',
        '太陽光パネル'                      => 'construction_equipment',
        '衛生設備工事'                      => 'construction_plumbing',
        '配管工事・給排水設備工事・通信設備工事・ガス工事' => 'construction_plumbing',
        '土木工事'                          => 'construction_civil',
        'その他土木工事'                    => 'construction_civil',
        '交通関連土木工事'                  => 'construction_civil',
        '解体工事'                          => 'construction_civil',
        '測量設計'                          => 'construction_civil',
        '土木設計'                          => 'construction_civil',
        '地質調査'                          => 'construction_civil',
        '非破壊検査'                        => 'construction_civil',
        'プラント設計'                      => 'construction_civil',
        'プラント設備工事'                  => 'construction_civil',
        '燃料タンク工事'                    => 'construction_civil',
        '仮設資材レンタル・リース'          => 'construction_scaffold',
        '足場工事'                          => 'construction_scaffold',
        '建設資材'                          => 'construction_civil',
        '金属系建材'                        => 'construction_civil',
        '木材系建材'                        => 'construction_civil',
        '窯業系建材・石材'                  => 'construction_civil',
        '樹脂系建材'                        => 'construction_civil',
        '建築設計'                          => 'construction_builder',
        '建築意匠設計'                      => 'construction_builder',
        '建築構造設計'                      => 'construction_builder',
        '建築材料'                          => 'construction_civil',
        '土木建築材料'                      => 'construction_civil',
        '内装工事・床工事・フローリング工事' => 'construction_reform',
        'インテリアデザイン'               => 'construction_reform',
        'インテリアコーディネーター'       => 'construction_reform',
        '店舗デザイン'                      => 'construction_reform',
        '店舗・商業施設'                    => 'construction_reform',
        'ビル・商業施設建設'               => 'construction_builder',
        'ビル建設'                          => 'construction_builder',
        '大型商業施設・公共施設建設'       => 'construction_builder',
        '商業施設企画・設計'               => 'construction_reform',
        '商業デザイン'                      => 'construction_reform',
        'その他建設・工事'                 => 'construction_civil',
        '駐車場・駐輪場開発'               => 'realestate_parking',
        '製図'                              => 'construction_civil',

        // ===== 不動産 =====
        '不動産売買・仲介'                  => 'realestate_sale',
        '土地売買'                          => 'realestate_sale',
        '総合不動産（デベロッパー）'       => 'realestate_land',
        'マンション開発'                    => 'realestate_land',
        '不動産鑑定'                        => 'realestate_sale',
        '不動産サブリース'                  => 'realestate_rental',
        '不動産賃貸・仲介'                  => 'realestate_rental',
        'マンション・ビル管理'             => 'realestate_rental',
        'ビルメンテナンス'                  => 'realestate_rental',
        '不動産管理'                        => 'realestate_rental',
        'レンタルスペース'                  => 'realestate_parking',
        '駐車場'                            => 'realestate_parking',
        'その他不動産'                      => 'realestate_sale',
        '不動産コンサルティング'            => 'realestate_sale',

        // ===== 士業・専門サービス =====
        '税理士'                            => 'prof_tax',
        '会計士'                            => 'prof_tax',
        '財務・監査コンサルティング'       => 'prof_tax',
        '監査法人'                          => 'prof_tax',
        '行政書士'                          => 'prof_judicial',
        '司法書士'                          => 'prof_judicial',
        '社会保険労務士'                    => 'prof_labor',
        '弁護士'                            => 'prof_lawyer',
        '土地家屋調査士'                    => 'prof_surveyor',
        '経営コンサルティング'             => 'prof_consultant',
        '総合コンサルティング'             => 'prof_consultant',
        'ITコンサルティング'               => 'prof_consultant',
        '組織・人事コンサルティング'       => 'prof_consultant',
        'その他コンサルティング'           => 'prof_consultant',
        '起業コンサルティング'             => 'prof_consultant',
        'コスト削減コンサルティング'       => 'prof_consultant',
        '中小企業診断士'                    => 'prof_consultant',
        'シンクタンク'                      => 'prof_consultant',
        '建築コンサルティング'             => 'construction_builder',
        '飲食店コンサルティング'           => 'food_cafe',
        '製造業コンサルティング'           => 'mfg_other',
        '医療系コンサルティング'           => 'medical_clinic',
        '環境コンサルティング'             => 'other_unknown',
        '資産運用コンサルティング'         => 'other_finance',
        '販売促進コンサルティング'         => 'btob_ad',
        'Web広告運用コンサルティング'      => 'btob_it',

        // ===== 医療・歯科 =====
        '病院・療養所'                      => 'medical_clinic',
        '調剤薬局'                          => 'medical_clinic',
        '人間ドック'                        => 'medical_clinic',
        '臨床検査・臨床試験'               => 'medical_clinic',
        '保険組合'                          => 'other_public',
        'メンタルヘルスケア・産業医'       => 'medical_clinic',
        '医療機器・器具メーカー'           => 'manufacturing',
        '医薬品メーカー'                    => 'manufacturing',
        '家庭用医療機器・介護用品'         => 'retail_goods',
        '調査・検査・研究'                  => 'other_unknown',
        'その他医療・福祉'                  => 'medical_clinic',

        // ===== 整体・治療院 =====
        '整体'                              => 'therapy_seitai',
        '接骨・柔道整復'                    => 'therapy_seikotsu',
        '鍼灸'                              => 'therapy_acupuncture',

        // ===== 介護・福祉 =====
        '介護'                              => 'care_elderly',
        '施設介護サービス'                  => 'care_elderly',
        '老人福祉・介護'                    => 'care_elderly',
        '在宅介護サービス'                  => 'care_visiting',
        '訪問看護'                          => 'care_visiting',
        '介護・福祉用品'                    => 'retail_goods',
        '介護用品メーカー'                  => 'manufacturing',
        '障害者福祉'                        => 'care_disability',
        '児童福祉'                          => 'care_therapy_child',

        // ===== 美容・サロン =====
        '美容院'                            => 'beauty_hair',
        '美容サロン'                        => 'beauty_hair',
        'エステティックサロン'             => 'beauty_esthetic',
        'エステサロン'                      => 'beauty_esthetic',

        // ===== 飲食 =====
        '和食'                              => 'food_japanese',
        '寿司'                              => 'food_japanese',
        'カフェ・喫茶店'                    => 'food_cafe',
        '洋食・レストラン'                  => 'food_restaurant',
        '居酒屋'                            => 'food_izakaya',
        '中華料理・ラーメン'               => 'food_ramen',
        'そば・うどん'                      => 'food_ramen',
        'ファーストフード'                  => 'food_takeout',
        '飲食宅配・弁当仕出し'             => 'food_takeout',
        'ケータリング'                      => 'food_takeout',
        '中食'                              => 'food_takeout',
        '給食調理・配食'                    => 'food_catering',
        '給食'                              => 'food_catering',
        'お菓子・スイーツ'                  => 'food_bakery',
        '焼肉'                              => 'food_yakiniku',
        'その他外食'                        => 'food_restaurant',

        // ===== 小売 =====
        'その他小売'                        => 'retail_goods',
        '化粧品販売'                        => 'retail_goods',
        '食品販売'                          => 'retail_food',
        '八百屋・鮮魚店'                    => 'retail_food',
        '牛乳宅配'                          => 'retail_food',
        'お菓子屋'                          => 'retail_food',
        'ガーデニング'                      => 'retail_flower',
        '花屋'                              => 'retail_flower',
        '雑貨販売'                          => 'retail_goods',
        '家具販売'                          => 'retail_goods',
        'アパレル販売'                      => 'retail_apparel',
        'レディースアパレルショップ'       => 'retail_apparel',
        'メンズアパレルショップ'           => 'retail_apparel',
        'キッズアパレルショップ'           => 'retail_apparel',
        'スポーツ用品ショップ'             => 'retail_sports',
        '眼鏡・コンタクトレンズ販売'      => 'retail_glasses',
        'ペットショップ'                    => 'retail_pet',
        '書店'                              => 'retail_book',
        '文房具販売'                        => 'retail_book',
        'ガソリンスタンド'                  => 'auto_repair',
        '自動車ディーラー'                  => 'auto_dealer',
        '中古車販売'                        => 'auto_used',
        'カー用品販売'                      => 'auto_dealer',
        'インターネット通販'               => 'retail_goods',
        '通信販売'                          => 'retail_goods',
        'カタログ通販'                      => 'retail_goods',
        'スーパー'                          => 'retail_food',
        'コンビニ'                          => 'retail_food',
        'ドラッグストア'                    => 'retail_goods',
        'ホームセンター'                    => 'retail_goods',
        'ショッピングセンター'             => 'retail_goods',
        '家電量販店'                        => 'retail_goods',
        '携帯ショップ'                      => 'retail_goods',
        '百貨店'                            => 'retail_goods',
        '楽器販売'                          => 'retail_goods',
        'ジュエリーショップ'               => 'retail_goods',
        '金券ショップ'                      => 'other_unknown',
        '古本・リサイクルショップ'         => 'retail_goods',
        '仏具・石材販売'                    => 'retail_goods',
        'お土産・ギフトショップ'           => 'retail_goods',
        'タバコ販売'                        => 'retail_goods',
        'レコード販売'                      => 'retail_goods',
        'パソコン・スマホ周辺機器販売'     => 'retail_goods',
        '自動販売機'                        => 'other_unknown',
        '新聞販売店'                        => 'retail_goods',
        '教材'                              => 'edu_vocational',

        // ===== 宿泊・観光・レジャー =====
        'ホテル'                            => 'lodging_hotel',
        '旅館'                              => 'lodging_hotel',
        '温泉施設'                          => 'lodging_hotel',
        '民泊運営代行'                      => 'lodging_guesthouse',
        '宿泊予約'                          => 'lodging_hotel',
        'レジャー・テーマパーク'           => 'lodging_experience',
        'ゴルフ場'                          => 'lodging_golf',
        '観光バス'                          => 'auto_transport',
        '景観地運営'                        => 'lodging_experience',
        '牧場'                              => 'agri_farm',
        '旅行'                              => 'lodging_hotel',
        '航空機チャーター・ヘリコプター・クルーザー' => 'other_unknown',
        'フィットネスクラブ'               => 'lodging_fitness',
        'スポーツ'                          => 'lodging_golf',
        'ボウリング場'                      => 'lodging_golf',
        'アミューズメント施設'             => 'lodging_experience',
        'ゴルフ場'                          => 'lodging_golf',

        // ===== 保育・教育 =====
        '児童保育'                          => 'edu_nursery',
        '保育・託児'                        => 'edu_nursery',
        '塾・受験予備校'                    => 'edu_cram',
        '各種スクール・教室（ビジネス）'   => 'edu_lesson',
        '各種スクール・教室（趣味）'       => 'edu_lesson',
        '語学学習スクール'                  => 'edu_language',
        '通信教育'                          => 'edu_vocational',
        '資格取得・通信教育'               => 'edu_vocational',
        '専門学校・専修学校'               => 'edu_vocational',
        '自動車教習所'                      => 'edu_vocational',
        '学校'                              => 'edu_cram',
        '教育教材'                          => 'edu_vocational',
        'その他教育業界'                    => 'edu_lesson',

        // ===== 自動車・輸送 =====
        '自動車'                            => 'auto_dealer',
        'レンタカー・リース'               => 'auto_rental',
        '二輪車'                            => 'auto_bike',
        '自動車整備'                        => 'auto_repair',
        '自動車部品・カー用品'             => 'auto_dealer',
        'トラック・バス'                    => 'auto_transport',
        'その他自動車'                      => 'auto_dealer',
        'ゴム・タイヤ'                      => 'auto_repair',
        'その他乗り物'                      => 'auto_transport',
        '造船'                              => 'other_unknown',
        '航空機'                            => 'other_unknown',
        '宇宙開発'                          => 'other_unknown',
        '鉄道車両'                          => 'other_unknown',

        // ===== 運輸・物流 =====
        '一般貨物輸送'                      => 'auto_transport',
        '陸運'                              => 'auto_transport',
        '冷凍冷蔵車運行'                    => 'auto_transport',
        '機械輸送'                          => 'auto_transport',
        '重量物輸送'                        => 'auto_transport',
        'バス'                              => 'auto_taxi',
        'タクシー'                          => 'auto_taxi',
        '鉄道'                              => 'other_public',
        '海運'                              => 'other_unknown',
        '空運'                              => 'other_unknown',
        '港湾運送'                          => 'other_unknown',
        '倉庫'                              => 'btob_cleaning',
        'その他運輸・物流'                  => 'auto_transport',

        // ===== 製造業 =====
        '金属加工'                          => 'mfg_metal',
        '金属部品'                          => 'mfg_metal',
        '機械部品'                          => 'mfg_metal',
        '精密機器'                          => 'mfg_metal',
        '金型'                              => 'mfg_metal',
        '切削工具'                          => 'mfg_metal',
        '工具'                              => 'mfg_metal',
        'ベアリング'                        => 'mfg_metal',
        '砥石・研磨材'                      => 'mfg_metal',
        '溶接機械'                          => 'mfg_metal',
        'ステンレス'                        => 'mfg_metal',
        '非鉄金属・鉱物製品'               => 'mfg_metal',
        'アルミニウム'                      => 'mfg_metal',
        '紙類包装資材'                      => 'mfg_print',
        'プラスチック包装資材'             => 'mfg_print',
        '印刷機械'                          => 'mfg_print',
        '化粧品製造'                        => 'beauty_esthetic',
        '繊維加工・織布'                    => 'mfg_other',
        '皮革'                              => 'mfg_other',
        '半導体'                            => 'mfg_metal',
        '防災・防犯機器'                    => 'mfg_other',
        '看板'                              => 'mfg_other',
        '作業関連用品'                      => 'mfg_other',
        '輸送用機械器具'                    => 'mfg_other',
        '舗装材料'                          => 'mfg_other',
        '舞台装置'                          => 'mfg_other',
        '駐車装置'                          => 'mfg_other',
        '消防用設備用品'                    => 'mfg_other',
        '耐火物'                            => 'mfg_other',
        '電設資材'                          => 'mfg_other',
        '農業用機械'                        => 'agri_farm',
        'その他製造'                        => 'mfg_other',

        // ===== 食品製造 =====
        '食肉'                              => 'mfg_food',
        '和菓子'                            => 'food_bakery',
        '洋菓子'                            => 'food_bakery',
        'パン'                              => 'food_bakery',
        '菓子'                              => 'food_bakery',
        'その他菓子'                        => 'food_bakery',
        '乳製品'                            => 'mfg_food',
        '水産'                              => 'agri_fish',
        '調味料'                            => 'mfg_food',
        '酒・ワイン'                        => 'retail_liquor',
        '飲料'                              => 'mfg_food',
        '農'                                => 'agri_farm',
        '健康食品'                          => 'mfg_food',
        '自然食品'                          => 'mfg_food',
        '缶詰・レトルト・冷凍食品'         => 'mfg_food',
        '冷凍食品'                          => 'mfg_food',
        '米飯・惣菜'                        => 'mfg_food',
        '麺類'                              => 'mfg_food',
        '漬物・煮物・大豆'                  => 'mfg_food',
        '製粉・食用油'                      => 'mfg_food',
        '食用油'                            => 'mfg_food',
        '製糖'                              => 'mfg_food',
        '茶・コーヒー'                      => 'mfg_food',
        '業務用食料品'                      => 'mfg_food',
        '畜産'                              => 'agri_farm',
        '養殖業'                            => 'agri_fish',
        '飼料'                              => 'agri_farm',
        'その他食品'                        => 'mfg_food',
        '食品宅配'                          => 'food_takeout',

        // ===== 機械 =====
        'センサー・計測機器'               => 'mfg_metal',
        '空調機器'                          => 'construction_equipment',
        '建設機械'                          => 'mfg_metal',
        '電力設備・発電設備'               => 'construction_equipment',
        '省エネ機器'                        => 'construction_equipment',
        '電子機器'                          => 'mfg_metal',
        'その他機械'                        => 'mfg_metal',
        '工作機械'                          => 'mfg_metal',
        '試験機'                            => 'mfg_metal',
        '農業機械'                          => 'agri_farm',
        '電気機器'                          => 'mfg_metal',
        '化学機械'                          => 'mfg_metal',
        '光学機器・レンズ'                  => 'mfg_metal',
        '業務厨房関連機器'                  => 'mfg_other',
        '動力装置'                          => 'mfg_metal',
        '産業用ロボット・ファクトリーオートメーション' => 'mfg_metal',
        '水処理機械'                        => 'mfg_other',
        '包装機械'                          => 'mfg_other',
        'プラスチック成形機械'             => 'mfg_other',
        '食品機械'                          => 'mfg_food',
        '油圧機器・空圧機器'               => 'mfg_metal',
        'アミューズメント機器'             => 'lodging_experience',
        '機械式駐車場'                      => 'realestate_parking',
        'エレベーター・エスカレーター'     => 'mfg_other',
        'ボイラー'                          => 'mfg_other',
        '排水処理機器'                      => 'mfg_other',
        '環境測定機'                        => 'mfg_other',
        'ポンプ'                            => 'mfg_other',
        '浄水器'                            => 'retail_goods',
        '自動販売機・自動サービス機'       => 'other_unknown',
        'フォークリフト'                    => 'mfg_other',
        '高所作業車'                        => 'construction_scaffold',
        '交通機器'                          => 'mfg_other',
        '蓄電池'                            => 'construction_equipment',
        'レーザー加工機'                    => 'mfg_metal',
        'レーザー加工'                      => 'mfg_metal',
        '半導体・半導体関連装置'           => 'mfg_metal',
        '半導体検査装置'                    => 'mfg_metal',
        '事務用機械器具'                    => 'btob_it',

        // ===== BtoB・法人サービス =====
        'その他サービス'                    => 'btob_cleaning',
        '検査'                              => 'btob_cleaning',
        '引越し'                            => 'btob_cleaning',
        '環境・廃棄物処理'                  => 'btob_cleaning',
        '廃水処理調査'                      => 'btob_cleaning',
        '葬儀'                              => 'other_unknown',
        'その他リース'                      => 'btob_cleaning',
        '警備'                              => 'btob_security',
        'オフィス用品リース'               => 'btob_cleaning',
        '生活関連リース'                    => 'btob_cleaning',
        'ビル・商業施設清掃'               => 'btob_cleaning',
        'ブライダル'                        => 'other_unknown',
        'クリーニング'                      => 'btob_cleaning',
        '水道'                              => 'construction_plumbing',
        'ガス'                              => 'other_unknown',
        '電力'                              => 'other_unknown',
        'パソコン・スマホ修理'             => 'btob_it',
        '家事代行'                          => 'btob_cleaning',
        '翻訳・通訳'                        => 'btob_ad',
        '営業代行・販売代行'               => 'btob_staffing',
        'データ入力・事務作業代行'         => 'btob_cleaning',
        '経理代行・記帳代行・決算代行・給与計算' => 'prof_tax',
        'アウトソーシング業務請負'         => 'btob_cleaning',
        'コールセンター・テレマーケティング' => 'btob_cleaning',
        '人事採用業務代行'                  => 'btob_staffing',
        '福利厚生代行'                      => 'btob_staffing',
        '便利業'                            => 'btob_cleaning',
        '秘書代行・電話代行'               => 'btob_cleaning',
        'テープ起こし'                      => 'btob_cleaning',
        'その他業務請負'                    => 'btob_cleaning',
        'クラウドワーク環境業務請負・在宅業務支援' => 'btob_cleaning',

        // ===== IT・Web =====
        'Webサービス・アプリ運営'          => 'btob_it',
        'サーバー・ネットワーク'           => 'btob_it',
        'システム開発'                      => 'btob_it',
        'ソフトウェア販売'                  => 'btob_it',
        'AI・人工知能'                      => 'btob_it',
        'スマートフォンアプリ'             => 'btob_it',
        'Webコンサルティング'              => 'btob_it',
        'システム受託開発'                  => 'btob_it',
        'eコマース'                         => 'btob_it',
        '情報セキュリティ'                  => 'btob_it',
        'クラウドサービス'                  => 'btob_it',
        'デジタルコンテンツ'               => 'btob_it',
        '自社型eコマース'                   => 'btob_it',
        'SaaS/ASPサービス運営'             => 'btob_it',
        'モール型eコマース'                 => 'btob_it',
        'その他IT・Web'                     => 'btob_it',

        // ===== 広告・制作 =====
        'デザイン'                          => 'btob_ad',
        '広告代理店'                        => 'btob_ad',
        '印刷'                              => 'btob_ad',
        '映像・CM制作'                      => 'btob_ad',
        '市場調査・リサーチ'               => 'btob_ad',
        'ノベルティ・オリジナルグッズ製作' => 'btob_ad',
        'コンテンツ企画・制作'             => 'btob_ad',
        'PR'                               => 'btob_ad',
        'ゲーム・アニメーション系デザイン' => 'btob_ad',
        'Webデザイン'                       => 'btob_it',
        'SP・セールスプロモーション'       => 'btob_ad',
        '広告制作'                          => 'btob_ad',
        'スタジオ・写真撮影'               => 'btob_ad',
        'CG制作'                            => 'btob_ad',
        'インターネット広告代理店'         => 'btob_it',
        'その他広告'                        => 'btob_ad',

        // ===== 人材 =====
        '人材派遣'                          => 'btob_staffing',
        '企業研修'                          => 'btob_staffing',
        '人材紹介'                          => 'btob_staffing',
        '求人広告代理店'                    => 'btob_ad',
        '職業紹介所'                        => 'btob_staffing',
        '求人媒体運営・求人情報誌出版'     => 'btob_staffing',
        'ヘッドハンティング'               => 'btob_staffing',
        '求人イベント・合同説明会'         => 'btob_staffing',
        'その他人材'                        => 'btob_staffing',

        // ===== アパレル・美容 =====
        '靴'                                => 'retail_apparel',
        'レディースアパレルメーカー'       => 'retail_apparel',
        'アパレル'                          => 'retail_apparel',
        'メンズアパレルメーカー'           => 'retail_apparel',
        'ジュエリー・アクセサリー'         => 'retail_goods',
        'スポーツウェアメーカー'           => 'retail_apparel',
        'バッグ・装飾品'                    => 'retail_goods',
        '化粧品'                            => 'retail_goods',
        '下着・靴下'                        => 'retail_apparel',
        '制服・作業服'                      => 'retail_apparel',
        '和服・呉服'                        => 'retail_apparel',
        '時計'                              => 'retail_goods',
        'めがね'                            => 'retail_glasses',
        'キッズ・ベビー・マタニティーアパレルメーカー' => 'retail_apparel',

        // ===== 商社 =====
        'その他専門商社'                    => 'btob_cleaning',
        '鉄鋼・金属専門商社'               => 'mfg_metal',
        '総合商社'                          => 'btob_cleaning',
        '工業用機械専門商社'               => 'mfg_metal',
        '建材専門商社'                      => 'construction_civil',
        '機械専門商社'                      => 'mfg_metal',
        '輸出入業務代行'                    => 'btob_cleaning',
        '電子部品専門商社'                  => 'mfg_metal',
        '医療関連専門商社'                  => 'medical_clinic',
        '日用品・化粧品専門商社'           => 'retail_goods',
        '化学専門商社'                      => 'mfg_other',
        '紙・パルプ専門商社'               => 'mfg_print',
        '雑貨専門商社'                      => 'retail_goods',
        '水産物食品専門商社'               => 'agri_fish',
        '燃料・エネルギー専門商社'         => 'other_unknown',
        '繊維・アパレル専門商社'           => 'retail_apparel',
        '食品専門商社'                      => 'mfg_food',
        'その他食品専門商社'               => 'mfg_food',
        'その他機械専門商社'               => 'mfg_metal',
        '農林水産用機械専門商社'           => 'agri_farm',
        '非鉄金属専門商社'                  => 'mfg_metal',
        '農産物食品専門商社'               => 'agri_farm',
        '食肉専門商社'                      => 'mfg_food',
        '医療機器・器具専門商社'           => 'medical_clinic',

        // ===== 資源・素材 =====
        '肥料・農薬'                        => 'agri_farm',
        '繊維'                              => 'mfg_other',
        '化学薬品'                          => 'mfg_other',
        '塗料'                              => 'construction_paint',
        'プラスチック製品'                  => 'mfg_other',
        '木材・パルプ'                      => 'agri_forest',
        '建築材料'                          => 'construction_civil',
        '硝子'                              => 'mfg_other',
        '鋼材'                              => 'mfg_metal',
        '工業用プラスチック製品加工'       => 'mfg_other',
        '金属製品'                          => 'mfg_metal',
        '樹脂製品'                          => 'mfg_other',
        '接着剤・テープ'                    => 'mfg_other',
        '化学品'                            => 'mfg_other',
        '石炭・鉱石'                        => 'other_unknown',
        'セメント'                          => 'mfg_other',
        '石油・石炭製品'                    => 'other_unknown',
        '潤滑油'                            => 'mfg_other',
        '香料'                              => 'mfg_other',
        '缶'                                => 'mfg_other',
        'ファインセラミックス'             => 'mfg_other',
        '油脂化学'                          => 'mfg_other',

        // ===== 生活用品 =====
        '玩具'                              => 'retail_goods',
        'スポーツ用品'                      => 'retail_sports',
        'ヘルスケア用品'                    => 'retail_goods',
        'ペット用品'                        => 'retail_pet',
        '日用品・生活用品'                  => 'retail_goods',
        '雑貨'                              => 'retail_goods',
        'アウトドア用品'                    => 'retail_sports',
        '厨房機器・用品'                    => 'retail_goods',
        'オフィス用品'                      => 'btob_cleaning',
        '家具・インテリア'                  => 'retail_goods',
        '文具・事務用品'                    => 'retail_book',
        '寝具'                              => 'retail_goods',
        '生花・プリザーブドフラワー'       => 'retail_flower',
        '防災用設備・用品'                  => 'retail_goods',
        'アロマ・フレグランス'             => 'retail_goods',
        '模型・プラモデル'                  => 'retail_goods',
        '電池・バッテリー'                  => 'retail_goods',
        '防犯用設備・用品'                  => 'retail_goods',
        '伝統工芸品・古美術'               => 'retail_goods',
        'タバコ'                            => 'retail_goods',
        '清掃用機械器具・用品'             => 'btob_cleaning',
        '美術品・伝統工芸品'               => 'retail_goods',
        'バス・トイレ・キッチン設備'       => 'construction_equipment',
        'スマートフォンアクセサリー'       => 'retail_goods',
        'パーティー用品'                    => 'retail_goods',
        '観葉植物・観賞魚'                  => 'retail_flower',
        'ベビー用品'                        => 'retail_goods',
        '眼鏡・コンタクトレンズ'           => 'retail_glasses',
        'トイレタリー'                      => 'retail_goods',
        '殺虫・殺そ(鼠）剤'               => 'retail_goods',
        '釣具'                              => 'retail_sports',
        'その他生活用品・嗜好品'           => 'retail_goods',
        '食器・キッチン用品'               => 'retail_goods',

        // ===== 家電 =====
        '総合家電メーカー'                  => 'mfg_other',
        'スマートフォン・タブレット周辺機器' => 'retail_goods',
        'カメラ'                            => 'retail_goods',
        'テレビ'                            => 'mfg_other',
        'エアコン'                          => 'construction_equipment',
        'パソコン'                          => 'btob_it',
        'AV機器'                            => 'retail_goods',
        '照明器具'                          => 'construction_equipment',
        'その他電気製品'                    => 'retail_goods',
        '生活家電'                          => 'retail_goods',
        'ディスプレイ・カメラ'             => 'retail_goods',
        '液晶ディスプレイ'                  => 'mfg_other',
        'キッチン家電'                      => 'retail_goods',
        'その他家電'                        => 'retail_goods',

        // ===== マスコミ・出版 =====
        '電子書籍出版'                      => 'btob_ad',
        '出版社'                            => 'btob_ad',
        'テレビ番組制作'                    => 'btob_ad',
        '芸能プロダクション'               => 'btob_ad',
        '新聞'                              => 'btob_ad',
        'ケーブルテレビ放送'               => 'btob_ad',
        'ラジオ番組制作'                    => 'btob_ad',
        'テレビ・ラジオ放送局'             => 'btob_ad',
        'その他マスコミ・出版'             => 'btob_ad',

        // ===== エンタメ =====
        'タレント・キャラクターグッズ'     => 'retail_goods',
        '楽器'                              => 'retail_goods',
        '企業展示会・販促イベント'         => 'btob_ad',
        '音楽'                              => 'edu_lesson',
        'イベント'                          => 'btob_ad',
        '映画・アニメ'                      => 'btob_ad',
        'パチンコ'                          => 'other_unknown',
        'その他エンタメ'                    => 'other_unknown',
        '映画館・劇場'                      => 'lodging_experience',
        'マルチメディア'                    => 'btob_it',
        '美術館'                            => 'other_public',
        'カラオケ'                          => 'lodging_experience',
        '占い'                              => 'other_unknown',
        'ホスト・キャバクラ'               => 'other_unknown',
        'まんが喫茶・インターネットカフェ' => 'lodging_experience',
        '劇団'                              => 'edu_lesson',

        // ===== ゲーム =====
        'ゲームソフト開発'                  => 'btob_it',
        'ソーシャルゲーム開発'             => 'btob_it',
        'ゲームソフト受託開発'             => 'btob_it',
        'その他ゲーム'                      => 'btob_it',

        // ===== 通信 =====
        'インターネットサービスプロバイダ' => 'btob_it',
        '携帯電話'                          => 'btob_it',
        'その他通信'                        => 'btob_it',
        'MVNO・格安SIM事業者'              => 'btob_it',
        '電話機・ビジネスフォン'           => 'btob_it',
        'コピー機・OA機器'                  => 'btob_it',

        // ===== 金融 =====
        '貸金'                              => 'other_finance',
        'クレジット・信販・決済代行'       => 'other_finance',
        '生命保険'                          => 'other_finance',
        '投資'                              => 'other_finance',
        'ネット証券'                        => 'other_finance',
        '保険代理店'                        => 'other_finance',
        '消費者金融'                        => 'other_finance',
        '損害保険'                          => 'other_finance',
        '保険'                              => 'other_finance',
        'その他金融関連サービス'           => 'other_finance',
        'ベンチャーキャピタル'             => 'other_finance',
        '証券'                              => 'other_finance',
        '債権回収・ファクタリング'         => 'other_finance',
        '信託銀行'                          => 'other_finance',
        '銀行'                              => 'other_finance',
        '信用金庫・信用組合'               => 'other_finance',
        '事業者金融'                        => 'other_finance',
        '不動産投資'                        => 'other_finance',
        'フィンテック'                      => 'other_finance',
        'ネット銀行'                        => 'other_finance',
        '地方銀行'                          => 'other_finance',

        // ===== エネルギー =====
        '再生可能エネルギー'               => 'construction_equipment',
        'ガス・燃料製品と原料採掘'         => 'other_unknown',
        '電力発電'                          => 'construction_equipment',
        'ソーラーシステム・太陽光発電'     => 'construction_equipment',
        '新電力'                            => 'other_unknown',
        'バイオ燃料'                        => 'other_unknown',
        'その他エネルギー'                  => 'other_unknown',

        // ===== 公共・団体 =====
        '社団法人'                          => 'other_public',
        '協会'                              => 'other_public',
        '財団法人'                          => 'other_public',
        '協同組合'                          => 'other_public',
        'NPO'                               => 'other_public',
        '官公庁・自治体・各種団体'         => 'other_public',
        '図書館'                            => 'other_public',
        '宗教団体'                          => 'other_religion',
        '都道府県機関'                      => 'other_public',
        'その他団体'                        => 'other_public',

        // ===== 農業・一次産業 =====
        '農業・直売所'                      => 'agri_farm',
        '林業・木材'                        => 'agri_forest',
    ];

    /**
     * BIZMAPSの大分類テキスト → TRUSTEPSのslug（中分類が見つからない場合のフォールバック）
     */
    private const PARENT_CATEGORY_MAP = [
        '建設・建築'                => 'construction_civil',
        '不動産'                    => 'realestate_sale',
        '士業'                      => 'prof_consultant',
        '医療・福祉業界'            => 'medical_clinic',
        '飲食業界'                  => 'food_restaurant',
        '生活関連サービス業'        => 'btob_cleaning',
        'アパレル・美容業界'        => 'beauty_hair',
        '小売・卸売業界'            => 'retail_goods',
        'レジャー・観光・宿泊'      => 'lodging_hotel',
        '教育・学習業界'            => 'edu_lesson',
        '自動車・輸送機器業界'      => 'auto_dealer',
        '製造業界'                  => 'mfg_other',
        '食品業界'                  => 'mfg_food',
        'IT・Web'                   => 'btob_it',
        'コンサルティング業界'      => 'prof_consultant',
        '商社業界'                  => 'btob_cleaning',
        'アウトソーシング・代行サービス' => 'btob_cleaning',
        '広告・制作業界'            => 'btob_ad',
        '機械業界'                  => 'mfg_metal',
        '機械関連サービス業界'      => 'mfg_metal',
        '運輸・物流業界'            => 'auto_transport',
        '資源・素材業界'            => 'mfg_other',
        '生活用品・嗜好品業界'      => 'retail_goods',
        '人材業界'                  => 'btob_staffing',
        '金融業界'                  => 'other_finance',
        '通信'                      => 'btob_it',
        '家電業界'                  => 'retail_goods',
        'マスコミ・出版業界'        => 'btob_ad',
        'エンタメ・娯楽'            => 'lodging_experience',
        'ゲーム業界'                => 'btob_it',
        'エネルギー業界'            => 'other_unknown',
        '公共機関・団体・特殊法人'  => 'other_public',
        'その他サービス業界'        => 'other_unknown',
        'その他業界'                => 'other_unknown',
    ];

    /**
     * BIZMAPSの業種テキストからTRUSTEPSのindustry slugを返す
     *
     * @param string $bizCategory  BIZMAPSの大分類テキスト
     * @param string|null $bizSubcategory BIZMAPSの中分類テキスト
     * @return string TRUSTEPSのindustry slug
     */
    public function resolve(string $bizCategory, ?string $bizSubcategory = null): string
    {
        // 中分類で先にマッチング
        if ($bizSubcategory) {
            $sub = trim($bizSubcategory);
            if (isset(self::SUBCATEGORY_MAP[$sub])) {
                return self::SUBCATEGORY_MAP[$sub];
            }
        }

        // 大分類でフォールバック
        $cat = trim($bizCategory);
        if (isset(self::PARENT_CATEGORY_MAP[$cat])) {
            return self::PARENT_CATEGORY_MAP[$cat];
        }

        return 'other_unknown';
    }

    /**
     * slugからindustry_idを引く（DBアクセスが必要な場合に使う）
     */
    public function resolveId(string $bizCategory, ?string $bizSubcategory = null): ?int
    {
        $slug = $this->resolve($bizCategory, $bizSubcategory);

        static $cache = [];
        if (!isset($cache[$slug])) {
            $industry = \DB::table('industries')->where('slug', $slug)->first();
            $cache[$slug] = $industry?->id;
        }

        return $cache[$slug];
    }
}
