<?php

return [
    'manual_url_limit' => 500,
    'high_fanout_threshold' => 5,
    'directory_link_limit' => 200,
    'directory_timeout' => 10,
    'directory_connect_timeout' => 5,
    'directory_user_agent' => 'TRUSTEPS-CMS-Lab-DiscoveryBot/0.18.5',
    'directory_detail_page_limit' => 50,
    'directory_detail_page_hard_limit' => 50,

    'official_site_resolver_url_limit' => 30,
    'official_site_resolver_timeout' => 10,
    'official_site_resolver_connect_timeout' => 5,
    'official_site_resolver_body_limit' => 1200000,
    'official_site_resolver_user_agent' => 'TRUSTEPS-CMS-Lab-OfficialSiteResolver/0.18.6',

    'directory_source_entry_url_limit' => 10,
    'directory_source_candidate_limit' => 200,
    'directory_source_excluded_limit' => 200,
    'directory_source_link_scan_limit' => 800,
    'directory_source_min_score' => 2,
    'directory_source_timeout' => 10,
    'directory_source_connect_timeout' => 5,
    'directory_source_body_limit' => 1200000,
    'directory_source_user_agent' => 'TRUSTEPS-CMS-Lab-DirectorySourceCollector/0.18.7',

    'directory_detail_positive_keywords' => [
        '株式会社', '有限会社', '合同会社', '工務店', '建設', '塗装', '設備', '電気', '商店', '会社',
        '事務所', '製作所', '製造', '介護', '福祉', '医院', 'クリニック', '旅館', 'ホテル', '農園',
        'member', 'members', 'shop', 'shops', 'company', 'office', 'detail', 'business', 'member-detail', 'kaiin', 'kamei',
    ],

    'directory_exclude_path_keywords' => [
        '/privacy', '/policy', '/contact', '/inquiry', '/login', '/logout', '/sitemap', '/site-map', '/news', '/blog',
        '/category', '/tag', '/wp-content', '/wp-admin', '/feed', '/rss', '/assets', '/css', '/js', '/images', '/image',
        '/about', '/access', '/recruit', '/entry', '/event', '/calendar', '/download', '/manual', '/search',
    ],

    'directory_exclude_text_keywords' => [
        'home', 'top', 'トップ', 'ホーム', 'お問い合わせ', '問合せ', 'プライバシー', '個人情報', 'サイトマップ',
        'アクセス', 'ログイン', '新着', 'お知らせ', 'もっと見る', '詳しくはこちら', '詳細はこちら', '詳細',
        '一覧', '戻る', '次へ', '前へ', '地図', 'map', 'facebook', 'instagram', 'twitter', 'x', 'youtube',
    ],

    'portal_domains' => [
        'tabelog.com',
        'hotpepper.jp',
        'beauty.hotpepper.jp',
        'suumo.jp',
        'homes.co.jp',
        'athome.co.jp',
        'carsensor.net',
        'goo-net.com',
        'jalan.net',
        'travel.rakuten.co.jp',
        'ekiten.jp',
        'navitime.co.jp',
        'mapion.co.jp',
        'itp.ne.jp',
        'townpage.goo.ne.jp',
        'iタウンページ.jp',
    ],

    'sns_domains' => [
        'instagram.com',
        'facebook.com',
        'twitter.com',
        'x.com',
        'youtube.com',
        'youtu.be',
        'tiktok.com',
        'line.me',
        'lin.ee',
        'note.com',
        'ameblo.jp',
    ],

    'builder_domains' => [
        'wixsite.com',
        'jimdo.com',
        'jimdosite.com',
        'jimdofree.com',
        'peraichi.com',
        'amebaownd.com',
        'ownd.site',
        'studio.site',
        'strikingly.com',
        'webnode.jp',
    ],

    'ec_domains' => [
        'base.shop',
        'thebase.in',
        'stores.jp',
        'stores.tokyo',
        'shopify.com',
        'myshopify.com',
        'rakuten.co.jp',
        'yahoo.co.jp',
        'shopping.yahoo.co.jp',
        'amazon.co.jp',
        'minne.com',
        'creema.jp',
    ],

    'map_domains' => [
        'maps.google.com',
        'google.com',
        'google.co.jp',
        'maps.app.goo.gl',
        'goo.gl',
    ],

    'shokokai_web_search_endpoint' => 'https://www12.shokokai.or.jp/hpsearch/top/php/search.php',
    'shokokai_web_search_timeout' => 12,
    'shokokai_web_search_connect_timeout' => 6,
    'shokokai_web_search_body_limit' => 1600000,
    'shokokai_web_search_user_agent' => 'TRUSTEPS-CMS-Lab-ShokokaiWebSearch/0.18.8',
    'shokokai_web_search_page_hard_limit' => 20,
    'shokokai_web_search_result_limit' => 500,
    'shokokai_web_search_prefectures' => [
        '01' => '北海道',
        '02' => '青森県',
        '03' => '岩手県',
        '04' => '宮城県',
        '05' => '秋田県',
        '06' => '山形県',
        '07' => '福島県',
        '08' => '茨城県',
        '09' => '栃木県',
        '10' => '群馬県',
        '11' => '埼玉県',
        '12' => '千葉県',
        '13' => '東京都',
        '14' => '神奈川県',
        '15' => '新潟県',
        '16' => '富山県',
        '17' => '石川県',
        '18' => '福井県',
        '19' => '山梨県',
        '20' => '長野県',
        '21' => '岐阜県',
        '22' => '静岡県',
        '23' => '愛知県',
        '24' => '三重県',
        '25' => '滋賀県',
        '26' => '京都府',
        '27' => '大阪府',
        '28' => '兵庫県',
        '29' => '奈良県',
        '30' => '和歌山県',
        '31' => '鳥取県',
        '32' => '島根県',
        '33' => '岡山県',
        '34' => '広島県',
        '35' => '山口県',
        '36' => '徳島県',
        '37' => '香川県',
        '38' => '愛媛県',
        '39' => '高知県',
        '40' => '福岡県',
        '41' => '佐賀県',
        '42' => '長崎県',
        '43' => '熊本県',
        '44' => '大分県',
        '45' => '宮崎県',
        '46' => '鹿児島県',
        '47' => '沖縄県',
    ],

];
