<?php
namespace App\Models;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
class HpFact extends Model
{
    use HasFactory;
    protected $fillable = [
        'hp_snapshot_id',
        'has_ec',
        'has_reservation',
        'has_recruiting',
        'has_portal_link',
        'has_sns_link',
        'has_google_business_link',
        'has_contact_form',
        'has_public_email',
        'has_phone',
        'hp_contact_email',
        'hp_contact_form_url',
        'hp_contact_phone',
        'contact_method_type',
        'update_status',
        'has_update_targets',
        'cms_type',
        'builder_type',
        'mobile_friendly',
        'ssl_enabled',
        'footer_year_status',
        'portal_dependency_level',
        'extractor_version',
        'extracted_at',
        'hp_title',
        'hp_description',
        'hp_last_modified',
        'hp_has_news',
        'hp_latest_post_date',
        'hp_update_staleness_days',
        'hp_page_count',
        'hp_has_map',
        'hp_image_count',
        'hp_word_count',
        'hp_has_tabelog',
        'hp_has_hotpepper',
        'hp_has_jalan',
        'hp_has_suumo',
        'hp_portal_links',
        'hp_improvement_score',
        'hp_js_rendering_required',
        // コンテンツ検出（Phase 2-A）
        'hp_has_case_studies',
        'hp_has_pricing',
        'hp_has_testimonials',
        'hp_has_faq',
        'hp_has_staff_intro',
        'hp_has_recruit_page',
        'hp_has_service_detail',
        'hp_has_company_profile',
        'hp_has_owner_name',
        'hp_has_local_keyword',
        // 2階層クロール（Phase 2-B）
        'hp_crawled_subpages',
        'hp_subpage_count',
    ];
    protected $casts = [
        'has_ec' => 'boolean',
        'has_reservation' => 'boolean',
        'has_recruiting' => 'boolean',
        'has_portal_link' => 'boolean',
        'has_sns_link' => 'boolean',
        'has_google_business_link' => 'boolean',
        'has_contact_form' => 'boolean',
        'has_public_email' => 'boolean',
        'has_phone' => 'boolean',
        'has_update_targets' => 'boolean',
        'mobile_friendly' => 'boolean',
        'ssl_enabled' => 'boolean',
        'extracted_at' => 'datetime',
        'hp_js_rendering_required' => 'boolean',
        'hp_has_case_studies' => 'boolean',
        'hp_has_pricing' => 'boolean',
        'hp_has_testimonials' => 'boolean',
        'hp_has_faq' => 'boolean',
        'hp_has_staff_intro' => 'boolean',
        'hp_has_recruit_page' => 'boolean',
        'hp_has_service_detail' => 'boolean',
        'hp_has_company_profile' => 'boolean',
        'hp_has_owner_name' => 'boolean',
        'hp_has_local_keyword' => 'boolean',
    ];
    public function snapshot()
    {
        return $this->belongsTo(HpSnapshot::class, 'hp_snapshot_id');
    }
}
